import { useState, useEffect, useCallback } from 'react';

/**
 * @description
 * React hook that synchronizes a stateful value with `localStorage`, providing a getter, setter, and remover. Keeps state in sync across browser tabs/windows and handles serialization, deserialization, and error cases gracefully.
 *
 * @param key - The `localStorage` key under which the value is stored.
 * @param defaultValue - The default value to use if the key does not exist or parsing fails.
 * @returns A tuple: `[storedValue, setValue, removeValue]` where:
 *   - `storedValue` is the current value from state/localStorage,
 *   - `setValue` updates both state and `localStorage` (accepts a value or updater function),
 *   - `removeValue` deletes the key from `localStorage` and resets state to `defaultValue`.
 *
 * @throws This hook does not throw, but logs errors to the console if `localStorage` access or JSON parsing fails.
 *
 * @example
 * ```tsx
 * const [user, setUser, removeUser] = useLocalStorage<User>('user', { name: '', age: 0 });
 *
 * // Set a new user
 * setUser({ name: 'Alice', age: 30 });
 *
 * // Update user with a function
 * setUser(prev => ({ ...prev, age: prev.age + 1 }));
 *
 * // Remove user from localStorage
 * removeUser();
 * ```
 *
 * @since 1.0.0
 * Generated by CodeRabbit
 */
export function useLocalStorage<T>(
  key: string,
  defaultValue: T
): [T, (value: T | ((val: T) => T)) => void, () => void] {
  // Get value from localStorage or use default
  const getStoredValue = useCallback((): T => {
    try {
      const item = window.localStorage.getItem(key);
      return item ? JSON.parse(item) : defaultValue;
    } catch (error) {
      console.error(`Error reading localStorage key "${key}":`, error);
      return defaultValue;
    }
  }, [key, defaultValue]);

  const [storedValue, setStoredValue] = useState<T>(getStoredValue);

  // Return a wrapped version of useState's setter function that persists to localStorage
  const setValue = useCallback(
    (value: T | ((val: T) => T)) => {
      try {
        // Allow value to be a function so we have same API as useState
        const valueToStore = value instanceof Function ? value(storedValue) : value;
        
        // Save state
        setStoredValue(valueToStore);
        
        // Save to local storage
        window.localStorage.setItem(key, JSON.stringify(valueToStore));
        
        // Dispatch storage event for other tabs/windows
        window.dispatchEvent(
          new StorageEvent('storage', {
            key,
            newValue: JSON.stringify(valueToStore),
            url: window.location.href,
          })
        );
      } catch (error) {
        console.error(`Error setting localStorage key "${key}":`, error);
      }
    },
    [key, storedValue]
  );

  // Remove value from localStorage
  const removeValue = useCallback(() => {
    try {
      window.localStorage.removeItem(key);
      setStoredValue(defaultValue);
      
      // Dispatch storage event for other tabs/windows
      window.dispatchEvent(
        new StorageEvent('storage', {
          key,
          newValue: null,
          url: window.location.href,
        })
      );
    } catch (error) {
      console.error(`Error removing localStorage key "${key}":`, error);
    }
  }, [key, defaultValue]);

  // Listen for changes in other tabs/windows
  useEffect(() => {
    const handleStorageChange = (e: StorageEvent) => {
      if (e.key === key && e.newValue !== null) {
        try {
          setStoredValue(JSON.parse(e.newValue));
        } catch (error) {
          console.error(`Error parsing localStorage value for key "${key}":`, error);
        }
      } else if (e.key === key && e.newValue === null) {
        setStoredValue(defaultValue);
      }
    };

    window.addEventListener('storage', handleStorageChange);
    return () => window.removeEventListener('storage', handleStorageChange);
  }, [key, defaultValue]);

  return [storedValue, setValue, removeValue];
}