import { useEffect } from 'react';
import useUIStore from '@/store/uiStore';

/**
 * @description
 * React hook that manages the application's theme based on user preference and system color scheme. It synchronizes the theme state with the system's dark mode setting when the theme is set to 'system', dynamically applying or removing the 'dark' CSS class on the document root element as needed.
 *
 * @returns An object containing the current theme and a function to update the theme.
 *
 * @example
 * const { theme, setTheme } = useTheme();
 * setTheme('dark'); // Switches to dark mode
 * setTheme('system'); // Follows system color scheme
 *
 * @since 1.0.0
 * Generated by CodeRabbit
 */
export function useTheme() {
  const { theme, setTheme } = useUIStore();

  useEffect(() => {
    const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)');
    
    const handleChange = () => {
      if (theme === 'system') {
        if (mediaQuery.matches) {
          document.documentElement.classList.add('dark');
        } else {
          document.documentElement.classList.remove('dark');
        }
      }
    };

    // Initial setup
    handleChange();

    // Listen for system theme changes
    mediaQuery.addEventListener('change', handleChange);

    return () => {
      mediaQuery.removeEventListener('change', handleChange);
    };
  }, [theme]);

  return { theme, setTheme };
}