# Hadolint configuration for Mobius project
# https://github.com/hadolint/hadolint

ignored:
  # Allow apt-get without version pinning during development
  - DL3008
  - DL3009 # Delete the apt-get lists after installing

trustedRegistries:
  - docker.io
  - gcr.io
  - quay.io
  - ghcr.io

# Override severity levels for Mobius security requirements
override:
  error:
    - DL3001 # Avoid using sudo in RUN
    - DL3002 # Last user should not be root
    - DL3003 # Use WORKDIR instead of cd
    - DL3004 # Do not use sudo
    - DL3025 # Use --no-cache-dir with pip
    - DL3020 # Use COPY instead of ADD for files and folders

  warning:
    - DL3013 # Pin versions in pip
    - DL3018 # Pin versions in apk add
    - DL3047 # Use COPY instead of ADD for archives
    - DL3059 # Multiple consecutive RUN instructions

  info:
    - DL3027 # Do not use apt
    - DL3045 # COPY with more than two arguments
