repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.4.4'
    hooks:
    -   id: ruff
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.1.0'
    hooks:
    -   id: prettier
-   repo: local
    hooks:
    -   id: check-env-files
        name: Check for .env files
        entry: scripts/pre-commit/check-env-files.sh
        language: script
        files: \.env$
    -   id: prepare-commit-msg
        name: Prepare commit message
        entry: scripts/prepare-commit-msg/create_session_commit.py
        language: python
        stages: [prepare-commit-msg]
