"""
FastAPI middleware for request/response logging.

This middleware provides:
- Request and response logging with timing
- Correlation ID generation and propagation
- Structured logging with context
- Error handling and logging
"""

import time
import uuid
from typing import Callable, Optional

import structlog
from fastapi import Request, Response
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.types import ASGIApp

from app.core.logging import LogConfig, get_logger


class LoggingMiddleware(BaseHTTPMiddleware):
    """Middleware for request/response logging with correlation IDs."""
    
    def __init__(self, app: ASGIApp, log_config: Optional[LogConfig] = None):
        """
        Initializes the LoggingMiddleware with the given ASGI application and optional logging configuration.
        
        Args:
            app (ASGIApp): The ASGI application instance to wrap with middleware.
            log_config (Optional[LogConfig]): Optional logging configuration. If not provided, a default LogConfig is used.
        
        Returns:
            None
        
        Example:
            middleware = LoggingMiddleware(app, log_config=my_log_config)
        
        Generated by CodeRabbit
        """
        super().__init__(app)
        self.log_config = log_config or LogConfig()
        self.logger = get_logger(__name__)
    
    async def dispatch(self, request: Request, call_next: Callable) -> Response:
        """
        Intercepts and processes each HTTP request, logging structured request and response details with correlation and request IDs.
        
        Args:
            request (Request): The incoming FastAPI request object.
            call_next (Callable): The next middleware or route handler to call.
        
        Returns:
            Response: The HTTP response generated by the downstream handler, with the correlation ID injected into the response headers.
        
        Raises:
            Exception: Propagates any exception raised during request processing after logging error details.
        
        Example:
            # Usage within FastAPI application setup
            app.add_middleware(LoggingMiddleware)
        
        Notes:
            - Binds correlation ID, request ID, HTTP method, path, and client host to the structured logging context.
            - Logs request start, completion (with status and duration), and errors with stack trace.
            - Correlation ID is extracted from headers or generated if absent; request ID is always generated.
            - Correlation ID is added to the response headers for traceability.
        
        Generated by CodeRabbit
        """
        # Generate or extract correlation ID
        correlation_id = request.headers.get(
            self.log_config.correlation_id_header,
            self._generate_correlation_id()
        )
        
        # Generate request ID
        request_id = self._generate_request_id()
        
        # Bind correlation ID and request context to logger
        structlog.contextvars.clear_contextvars()
        structlog.contextvars.bind_contextvars(
            correlation_id=correlation_id,
            request_id=request_id,
            method=request.method,
            path=str(request.url.path),
            client_host=request.client.host if request.client else None,
        )
        
        # Log request
        start_time = time.time()
        self.logger.info(
            "request_started",
            headers=dict(request.headers),
            query_params=dict(request.query_params),
        )
        
        try:
            # Process request
            response = await call_next(request)
            
            # Calculate duration
            duration_ms = (time.time() - start_time) * 1000
            
            # Log response
            self.logger.info(
                "request_completed",
                status_code=response.status_code,
                duration_ms=round(duration_ms, 2),
            )
            
            # Add correlation ID to response headers
            response.headers[self.log_config.correlation_id_header] = correlation_id
            
            return response
            
        except Exception as e:
            # Calculate duration even for errors
            duration_ms = (time.time() - start_time) * 1000
            
            # Log error
            self.logger.error(
                "request_failed",
                status_code=500,
                duration_ms=round(duration_ms, 2),
                error=str(e),
                exc_info=True,
            )
            
            # Re-raise the exception to let FastAPI handle it
            raise
    
    def _generate_correlation_id(self) -> str:
        """
        Generates a unique correlation ID as a UUID string.
        
        Returns:
            str: A newly generated UUID string to be used as a correlation ID.
        
        Generated by CodeRabbit
        """
        return str(uuid.uuid4())
    
    def _generate_request_id(self) -> str:
        """
        Generates a unique request ID as an 8-character string.
        
        Returns:
            str: An 8-character string derived from a newly generated UUID, used to uniquely identify each request.
        
        Generated by CodeRabbit
        """
        return str(uuid.uuid4())[:8]