name: Docker Linting

on:
  pull_request:
    paths:
      - 'docker/**'
      - 'docker-compose*.yml'
      - '.dockerignore'
      - '.hadolint.yaml'
      - '.dive-ci.yaml'
  push:
    branches:
      - main
      - develop
    paths:
      - 'docker/**'
      - 'docker-compose*.yml'
      - '.dockerignore'
      - '.hadolint.yaml'
      - '.dive-ci.yaml'

jobs:
  hadolint:
    name: Hadolint Dockerfile Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Hadolint on Backend Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/backend/Dockerfile
          config: .hadolint.yaml

      - name: Run Hadolint on Frontend Development Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/frontend/Dockerfile.dev
          config: .hadolint.yaml

      - name: Run Hadolint on Frontend Production Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/frontend/Dockerfile
          config: .hadolint.yaml

  docker-compose-validate:
    name: Docker Compose Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate Docker Compose files
        run: |
          # Validate development docker-compose (has defaults)
          echo "Validating docker-compose.yml..."
          docker compose -f docker-compose.yml config > /dev/null

          # Validate production docker-compose with required env vars
          # These are dummy values just for validation - not used in actual deployment
          echo "Validating docker-compose.prod.yml..."
          export POSTGRES_USER="${{ secrets.PROD_POSTGRES_USER || 'ci_validation' }}"
          export POSTGRES_PASSWORD="${{ secrets.PROD_POSTGRES_PASSWORD || 'ci_validation_password' }}"
          export REDIS_PASSWORD="${{ secrets.PROD_REDIS_PASSWORD || 'ci_validation_redis_password' }}"
          export QDRANT_API_KEY="${{ secrets.PROD_QDRANT_API_KEY || 'ci_validation_qdrant_key' }}"

          # Additional variables that might be needed
          export POSTGRES_DB="${{ secrets.PROD_POSTGRES_DB || 'mobius' }}"
          export MOBIUS_ALLOWED_ORIGINS="${{ secrets.PROD_MOBIUS_ALLOWED_ORIGINS || 'http://localhost:3000,http://localhost:8000' }}"

          docker compose -f docker-compose.prod.yml config > /dev/null
          echo "✓ All docker-compose files validated successfully"

  dive-analysis:
    name: Dive Image Analysis
    runs-on: ubuntu-latest
    # Only run on main branch pushes to avoid building on every PR
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Build Backend Image
        run: docker build -f docker/backend/Dockerfile -t mobius-backend:ci .

      - name: Run Dive on Backend
        uses: yuichielectric/dive-action@0.0.4
        with:
          image: 'mobius-backend:ci'
          config: '.dive-ci.yaml'

      - name: Build Frontend Image
        run: docker build -f docker/frontend/Dockerfile -t mobius-frontend:ci .

      - name: Run Dive on Frontend
        uses: yuichielectric/dive-action@0.0.4
        with:
          image: 'mobius-frontend:ci'
          config: '.dive-ci.yaml'

  security-scan:
    name: Security Scan with Trivy
    runs-on: ubuntu-latest
    # Only run on main branch pushes
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Build Backend Image
        run: docker build -f docker/backend/Dockerfile -t mobius-backend:ci .

      - name: Run Trivy vulnerability scanner on Backend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'mobius-backend:ci'
          format: 'sarif'
          output: 'trivy-backend-results.sarif'

      - name: Upload Backend Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-backend-results.sarif'

      - name: Build Frontend Image
        run: docker build -f docker/frontend/Dockerfile -t mobius-frontend:ci .

      - name: Run Trivy vulnerability scanner on Frontend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'mobius-frontend:ci'
          format: 'sarif'
          output: 'trivy-frontend-results.sarif'

      - name: Upload Frontend Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-frontend-results.sarif'
